basePath: /songs
definitions:
  model.Song:
    properties:
      group:
        type: string
      id:
        type: integer
      link:
        type: string
      name:
        type: string
      releaseDate:
        type: string
      text:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: Реализация онлайн библиотеки песен
  title: Тестовое API
paths:
  /songs:
    get:
      consumes:
      - application/json
      description: Просмотр всех песен с пагинацией и фильтрацией данных
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Количество элементов на странице
        in: query
        name: limit
        type: integer
      - description: Название группы
        in: query
        name: group
        type: string
      - description: Дата релиза
        in: query
        name: releasedate
        type: string
      produces:
      - application/json
      responses: {}
      summary: Все песни
  /songs/{id}:
    get:
      description: Информация песни по id
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Песня
  /songs/change/{id}:
    put:
      consumes:
      - application/json
      description: измение информации песни по id
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      - description: Информация о песне
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/model.Song'
      produces:
      - application/json
      responses: {}
      summary: Изменение песни
  /songs/create:
    post:
      consumes:
      - application/json
      description: Добавление песни по получаемым параметрам в JSON
      parameters:
      - description: Информация о песне
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/model.Song'
      produces:
      - application/json
      responses: {}
      summary: Добавление песни
  /songs/delete/{id}:
    delete:
      description: удвление песни по параметру запроса (id)
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Удаление песни
swagger: "2.0"
